version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../deployment/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
